on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [oldstable, stable]
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test -cover -coverprofile=coverage -covermode=atomic ./...
    - name: Upload code coverage
      if: matrix.platform == 'ubuntu-latest' && matrix.goversion=='stable'
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage
